<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="WatchDog.NET" Version="1.4.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarsXApps.Models\MarsXApps.Models.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\MarsXApps.AfterSaleService\MarsXApps.Module.ServiceAfterSale.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\MarsXApps.Module.NotificationMessage\MarsXApps.Module.NotificationMessage.csproj" />
    <ProjectReference Include="..\MarsXApps.Module.Promotion\MarsXApps.Module.Promotion.csproj" />
    <ProjectReference Include="..\MarsXApps.Module.ServicePrice\MarsXApps.Module.ServicePrice.csproj" />
    <ProjectReference Include="..\MarsXApps.Module.Posting\MarsXApps.Module.Posting.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Helper\" />
    <None Remove="Auth\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Helper\" />
    <Folder Include="Auth\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.IdentityModel.Tokens, Version=7.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
  </ItemGroup>
</Project>
