<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Repositories\" />
    <None Remove="Helper\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="Helper\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarsXApps.Models\MarsXApps.Models.csproj" />
    <ProjectReference Include="..\MarsXApps.Service\MarsXApps.Service.csproj" />
    <ProjectReference Include="..\MarsXApps.Module.SMS\MarsXApps.Module.SMS.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.2" />
  </ItemGroup>
</Project>
